// Professional Medical Knowledge Base
export interface MedicalCondition {
  name: string;
  symptoms: string[];
  severity: number; // 0-100
  category: 'cardiac' | 'respiratory' | 'gastrointestinal' | 'neurological' | 'infectious' | 'trauma' | 'metabolic' | 'dermatological' | 'other';
  riskFactors: string[];
  diagnosticCriteria: string[];
  medicines?: Array<{ name: string; dosage: string }>; // Optional medicines
  description?: string; // Optional description
  complications?: string[]; // Optional complications
}

export interface MedicineRecommendation {
  name: string;
  dosage: string;
  frequency: string;
  duration: string;
  contraindications: string[];
  sideEffects: string[];
  instructions: string;
}

export const MEDICAL_CONDITIONS: MedicalCondition[] = [
  // CRITICAL CARDIAC CONDITIONS
  {
    name: 'Acute Myocardial Infarction (Heart Attack)',
    symptoms: ['chest pain', 'radiating pain', 'left arm pain', 'jaw pain', 'sweating', 'nausea', 'shortness of breath', 'anxiety'],
    severity: 98,
    category: 'cardiac',
    riskFactors: ['smoking', 'diabetes', 'hypertension', 'high cholesterol', 'family history', 'obesity', 'age > 45'],
    diagnosticCriteria: ['crushing chest pain > 20 min', 'pain radiating to left arm/jaw', 'profuse sweating', 'ECG changes'],
    medicines: [
      { name: 'Aspirin', dosage: '300mg' },
      { name: 'Morphine', dosage: '5mg IV' },
      { name: 'Nitroglycerin', dosage: '0.4mg sublingual' },
    ],
    description: 'A heart attack occurs when a coronary artery supplying blood to the heart muscle is blocked, leading to tissue damage or death.',
    complications: ['Heart failure', 'Arrhythmias', 'Cardiogenic shock'],
  },
  {
    name: 'Unstable Angina',
    symptoms: ['chest pain', 'chest tightness', 'shortness of breath', 'pain on exertion'],
    severity: 85,
    category: 'cardiac',
    riskFactors: ['coronary artery disease', 'smoking', 'diabetes'],
    diagnosticCriteria: ['chest pain at rest', 'increasing frequency/severity', 'not relieved by rest'],
    medicines: [
      { name: 'Nitroglycerin', dosage: '0.4mg sublingual' },
      { name: 'Aspirin', dosage: '300mg' },
      { name: 'Morphine', dosage: '5mg IV' },
    ],
    description: 'Unstable angina is a type of chest pain that is more severe, lasts longer, or occurs more frequently than stable angina.',
    complications: ['Heart attack', 'Arrhythmias'],
  },

  // RESPIRATORY EMERGENCIES
  {
    name: 'Acute Respiratory Distress Syndrome (ARDS)',
    symptoms: ['severe breathlessness', 'rapid breathing', 'confusion', 'extreme fatigue', 'blue lips'],
    severity: 95,
    category: 'respiratory',
    riskFactors: ['pneumonia', 'sepsis', 'trauma', 'aspiration'],
    diagnosticCriteria: ['acute onset < 7 days', 'bilateral lung infiltrates', 'severe hypoxemia'],
    medicines: [
      { name: 'Oxygen', dosage: 'High flow' },
      { name: 'Morphine', dosage: '5mg IV' },
      { name: 'Furosemide', dosage: '40mg IV' },
    ],
    description: 'ARDS is a serious lung condition that causes rapid breathing and low oxygen levels in the blood.',
    complications: ['Respiratory failure', 'Multi-organ dysfunction'],
  },
  {
    name: 'Severe Asthma Attack (Status Asthmaticus)',
    symptoms: ['difficulty breathing', 'wheezing', 'chest tightness', 'inability to speak', 'cyanosis'],
    severity: 90,
    category: 'respiratory',
    riskFactors: ['asthma history', 'allergen exposure', 'respiratory infection'],
    diagnosticCriteria: ['severe airflow obstruction', 'not responding to bronchodilators', 'accessory muscle use'],
    medicines: [
      { name: 'Salbutamol', dosage: '2-4 puffs' },
      { name: 'Methylprednisolone', dosage: '125mg IV' },
      { name: 'Oxygen', dosage: 'High flow' },
    ],
    description: 'Status asthmaticus is a severe asthma attack that does not respond to usual treatments and requires immediate medical attention.',
    complications: ['Respiratory failure', 'Cardiac arrhythmias'],
  },
  {
    name: 'Pulmonary Embolism',
    symptoms: ['sudden breathlessness', 'chest pain', 'cough with blood', 'rapid heart rate', 'fainting'],
    severity: 92,
    category: 'respiratory',
    riskFactors: ['prolonged immobility', 'surgery', 'pregnancy', 'cancer', 'DVT history'],
    diagnosticCriteria: ['sudden onset dyspnea', 'pleuritic chest pain', 'tachycardia', 'hypoxemia'],
    medicines: [
      { name: 'Tinzaparin', dosage: '100IU/kg SC' },
      { name: 'Oxygen', dosage: 'High flow' },
      { name: 'Morphine', dosage: '5mg IV' },
    ],
    description: 'Pulmonary embolism is a blockage in the pulmonary artery, usually by a blood clot, leading to severe breathing difficulties.',
    complications: ['Pulmonary hypertension', 'Right-sided heart failure'],
  },

  // NEUROLOGICAL CONDITIONS
  {
    name: 'Acute Stroke (Cerebrovascular Accident)',
    symptoms: ['sudden weakness', 'facial drooping', 'speech difficulty', 'confusion', 'severe headache', 'vision problems', 'dizziness'],
    severity: 96,
    category: 'neurological',
    riskFactors: ['hypertension', 'atrial fibrillation', 'diabetes', 'smoking', 'age > 55'],
    diagnosticCriteria: ['FAST: Face drooping, Arm weakness, Speech difficulty, Time critical'],
    medicines: [
      { name: 'Alteplase', dosage: '0.9mg/kg IV' },
      { name: 'Aspirin', dosage: '300mg' },
      { name: 'Morphine', dosage: '5mg IV' },
    ],
    description: 'A stroke occurs when the blood supply to part of the brain is interrupted or reduced, leading to tissue damage or death.',
    complications: ['Paralysis', 'Speech difficulties', 'Memory loss'],
  },
  {
    name: 'Subarachnoid Hemorrhage',
    symptoms: ['thunderclap headache', 'worst headache ever', 'neck stiffness', 'vomiting', 'photophobia', 'loss of consciousness'],
    severity: 94,
    category: 'neurological',
    riskFactors: ['aneurysm', 'hypertension', 'smoking', 'family history'],
    diagnosticCriteria: ['sudden severe headache', 'meningeal signs', 'altered consciousness'],
    medicines: [
      { name: 'Labetalol', dosage: '10mg IV' },
      { name: 'Morphine', dosage: '5mg IV' },
      { name: 'Furosemide', dosage: '40mg IV' },
    ],
    description: 'Subarachnoid hemorrhage is bleeding in the space between the brain and the tissues covering the brain.',
    complications: ['Rebleeding', 'Hydrocephalus', 'Brain damage'],
  },
  {
    name: 'Meningitis',
    symptoms: ['severe headache', 'fever', 'neck stiffness', 'photophobia', 'confusion', 'vomiting', 'rash'],
    severity: 88,
    category: 'neurological',
    riskFactors: ['immunocompromised', 'crowded living', 'no vaccination'],
    diagnosticCriteria: ['fever + headache + neck stiffness', 'altered mental status', 'petechial rash'],
    medicines: [
      { name: 'Ceftriaxone', dosage: '2g IV' },
      { name: 'Dexamethasone', dosage: '10mg IV' },
      { name: 'Morphine', dosage: '5mg IV' },
    ],
    description: 'Meningitis is an inflammation of the protective membranes covering the brain and spinal cord.',
    complications: ['Seizures', 'Hearing loss', 'Brain damage'],
  },
  {
    name: 'Migraine',
    symptoms: ['throbbing headache', 'unilateral pain', 'nausea', 'photophobia', 'phonophobia', 'visual aura'],
    severity: 45,
    category: 'neurological',
    riskFactors: ['family history', 'stress', 'hormonal changes', 'certain foods'],
    diagnosticCriteria: ['recurrent attacks', 'unilateral pulsating pain', '4-72 hours duration'],
    medicines: [
      { name: 'Sumatriptan', dosage: '50mg IM' },
      { name: 'Metoclopramide', dosage: '10mg IV' },
      { name: 'Oxygen', dosage: 'High flow' },
    ],
    description: 'Migraine is a type of headache that can cause severe throbbing pain or a pulsing sensation, usually on one side of the head.',
    complications: ['Chronic migraines', 'Migraine aura'],
  },

  // INFECTIOUS DISEASES
  {
    name: 'Dengue Fever',
    symptoms: ['high fever', 'severe headache', 'retro-orbital pain', 'joint pain', 'muscle pain', 'rash', 'mild bleeding'],
    severity: 75,
    category: 'infectious',
    riskFactors: ['mosquito bite', 'endemic area', 'rainy season'],
    diagnosticCriteria: ['fever + 2 of: headache, retro-orbital pain, myalgia, arthralgia, rash, hemorrhage'],
    medicines: [
      { name: 'Paracetamol', dosage: '500-1000mg' },
      { name: 'Oxygen', dosage: 'High flow' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Dengue fever is a viral infection transmitted by mosquitoes, causing high fever, severe headache, and joint pain.',
    complications: ['Dengue hemorrhagic fever', 'Dengue shock syndrome'],
  },
  {
    name: 'Dengue Hemorrhagic Fever',
    symptoms: ['high fever', 'bleeding gums', 'blood in vomit', 'black stools', 'severe abdominal pain', 'persistent vomiting', 'cold extremities'],
    severity: 92,
    category: 'infectious',
    riskFactors: ['previous dengue infection', 'second infection'],
    diagnosticCriteria: ['thrombocytopenia', 'plasma leakage', 'hemorrhagic manifestations', 'organ impairment'],
    medicines: [
      { name: 'Paracetamol', dosage: '500-1000mg' },
      { name: 'Oxygen', dosage: 'High flow' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Dengue hemorrhagic fever is a severe form of dengue infection that can lead to bleeding, shock, and organ failure.',
    complications: ['Dengue shock syndrome', 'Multi-organ failure'],
  },
  {
    name: 'Typhoid Fever',
    symptoms: ['sustained fever', 'headache', 'abdominal pain', 'constipation or diarrhea', 'rose spots', 'weakness'],
    severity: 70,
    category: 'infectious',
    riskFactors: ['contaminated food/water', 'poor sanitation', 'endemic area'],
    diagnosticCriteria: ['sustained fever > 39°C', 'stepladder fever pattern', 'relative bradycardia'],
    medicines: [
      { name: 'Ciprofloxacin', dosage: '500mg IV' },
      { name: 'Oxygen', dosage: 'High flow' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Typhoid fever is a bacterial infection caused by Salmonella Typhi, leading to high fever, abdominal pain, and diarrhea.',
    complications: ['Perforated bowel', 'Septicemia'],
  },
  {
    name: 'Malaria',
    symptoms: ['cyclic fever', 'chills', 'sweating', 'headache', 'nausea', 'body ache', 'fatigue'],
    severity: 72,
    category: 'infectious',
    riskFactors: ['mosquito bite', 'endemic area', 'no prophylaxis'],
    diagnosticCriteria: ['fever with chills', 'periodicity', 'splenomegaly', 'positive blood smear'],
    medicines: [
      { name: 'Artemether-Lumefantrine', dosage: '6mg/kg' },
      { name: 'Oxygen', dosage: 'High flow' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Malaria is a parasitic infection transmitted by mosquitoes, causing cyclic fever, chills, and anemia.',
    complications: ['Cerebral malaria', 'Multi-organ failure'],
  },
  {
    name: 'COVID-19',
    symptoms: ['fever', 'dry cough', 'fatigue', 'loss of taste', 'loss of smell', 'shortness of breath', 'body ache'],
    severity: 65,
    category: 'infectious',
    riskFactors: ['exposure', 'crowded places', 'no vaccination', 'immunocompromised'],
    diagnosticCriteria: ['fever + respiratory symptoms', 'positive RT-PCR', 'close contact history'],
    medicines: [
      { name: 'Remdesivir', dosage: '200mg IV' },
      { name: 'Dexamethasone', dosage: '10mg IV' },
      { name: 'Oxygen', dosage: 'High flow' },
    ],
    description: 'COVID-19 is a viral infection caused by SARS-CoV-2, leading to respiratory symptoms and systemic effects.',
    complications: ['Pneumonia', 'Acute respiratory distress syndrome'],
  },
  {
    name: 'Tuberculosis',
    symptoms: ['persistent cough', 'cough with blood', 'night sweats', 'weight loss', 'fever', 'chest pain'],
    severity: 68,
    category: 'infectious',
    riskFactors: ['HIV', 'immunosuppression', 'close contact', 'crowded living'],
    diagnosticCriteria: ['cough > 2 weeks', 'weight loss', 'night sweats', 'positive sputum test'],
    medicines: [
      { name: 'Isoniazid', dosage: '300mg' },
      { name: 'Rifampicin', dosage: '600mg' },
      { name: 'Ethambutol', dosage: '1200mg' },
    ],
    description: 'Tuberculosis is a bacterial infection that primarily affects the lungs, causing persistent cough, fever, and weight loss.',
    complications: ['Miliary tuberculosis', 'Lymphadenopathy'],
  },
  {
    name: 'Pneumonia',
    symptoms: ['cough with phlegm', 'fever', 'chest pain', 'shortness of breath', 'rapid breathing', 'confusion (elderly)'],
    severity: 73,
    category: 'respiratory',
    riskFactors: ['elderly', 'smoking', 'chronic lung disease', 'immunocompromised'],
    diagnosticCriteria: ['fever + cough + dyspnea', 'chest X-ray infiltrates', 'crackles on auscultation'],
    medicines: [
      { name: 'Azithromycin', dosage: '500mg' },
      { name: 'Oxygen', dosage: 'High flow' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Pneumonia is an infection of the lungs, causing cough, fever, and difficulty breathing.',
    complications: ['Pleural effusion', 'Respiratory failure'],
  },

  // GASTROINTESTINAL CONDITIONS
  {
    name: 'Acute Appendicitis',
    symptoms: ['right lower quadrant pain', 'nausea', 'vomiting', 'fever', 'loss of appetite', 'rebound tenderness'],
    severity: 80,
    category: 'gastrointestinal',
    riskFactors: ['age 10-30', 'family history'],
    diagnosticCriteria: ['McBurney point tenderness', 'migration of pain', 'elevated WBC'],
    medicines: [
      { name: 'Opioids', dosage: 'IV' },
      { name: 'Antibiotics', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Acute appendicitis is inflammation of the appendix, causing severe pain in the lower right abdomen.',
    complications: ['Perforation', 'Abscess'],
  },
  {
    name: 'Acute Pancreatitis',
    symptoms: ['severe upper abdominal pain', 'radiating to back', 'nausea', 'vomiting', 'fever', 'rapid pulse'],
    severity: 85,
    category: 'gastrointestinal',
    riskFactors: ['gallstones', 'alcohol', 'high triglycerides'],
    diagnosticCriteria: ['severe epigastric pain', 'elevated amylase/lipase', 'imaging findings'],
    medicines: [
      { name: 'Opioids', dosage: 'IV' },
      { name: 'Antibiotics', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Acute pancreatitis is inflammation of the pancreas, causing severe abdominal pain and nausea.',
    complications: ['Pseudocyst', 'Pancreatic necrosis'],
  },
  {
    name: 'Acute Gastroenteritis',
    symptoms: ['diarrhea', 'vomiting', 'abdominal cramps', 'fever', 'nausea'],
    severity: 50,
    category: 'gastrointestinal',
    riskFactors: ['contaminated food/water', 'poor hygiene'],
    diagnosticCriteria: ['acute onset diarrhea', '> 3 loose stools/day', 'nausea/vomiting'],
    medicines: [
      { name: 'ORS', dosage: '200-400ml after each loose stool' },
      { name: 'Antibiotics', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Acute gastroenteritis is an infection of the stomach and intestines, causing diarrhea, vomiting, and abdominal pain.',
    complications: ['Dehydration', 'Electrolyte imbalance'],
  },
  {
    name: 'Peptic Ulcer Disease',
    symptoms: ['burning stomach pain', 'bloating', 'heartburn', 'nausea', 'dark stools'],
    severity: 55,
    category: 'gastrointestinal',
    riskFactors: ['H. pylori', 'NSAID use', 'smoking', 'alcohol', 'stress'],
    diagnosticCriteria: ['epigastric pain 1-3 hours after meals', 'relieved by food/antacids'],
    medicines: [
      { name: 'Proton pump inhibitors', dosage: 'IV' },
      { name: 'Antibiotics', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Peptic ulcer disease is a sore in the lining of the stomach or the first part of the small intestine.',
    complications: ['Bleeding', 'Perforation'],
  },
  {
    name: 'GERD (Acid Reflux)',
    symptoms: ['heartburn', 'regurgitation', 'chest pain', 'difficulty swallowing', 'chronic cough'],
    severity: 35,
    category: 'gastrointestinal',
    riskFactors: ['obesity', 'smoking', 'pregnancy', 'hiatal hernia'],
    diagnosticCriteria: ['heartburn > 2 times/week', 'regurgitation', 'response to PPI'],
    medicines: [
      { name: 'Proton pump inhibitors', dosage: 'IV' },
      { name: 'Antacids', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Gastroesophageal reflux disease (GERD) is a chronic condition where stomach acid flows back into the esophagus.',
    complications: ['Esophagitis', 'Barrett\'s esophagus'],
  },

  // TRAUMA & INJURIES
  {
    name: 'Severe Hemorrhage',
    symptoms: ['heavy bleeding', 'rapid pulse', 'low blood pressure', 'cold skin', 'confusion', 'weakness'],
    severity: 94,
    category: 'trauma',
    riskFactors: ['trauma', 'anticoagulants', 'bleeding disorder'],
    diagnosticCriteria: ['blood loss > 750ml', 'shock signs', 'tachycardia > 100'],
    medicines: [
      { name: 'Oxygen', dosage: 'High flow' },
      { name: 'Fluids', dosage: 'IV' },
      { name: 'Blood transfusion', dosage: 'IV' },
    ],
    description: 'Severe hemorrhage is excessive bleeding that can lead to shock and organ failure.',
    complications: ['Hypovolemic shock', 'Organ failure'],
  },
  {
    name: 'Fracture',
    symptoms: ['severe pain', 'swelling', 'deformity', 'inability to move', 'bruising', 'bone visible'],
    severity: 70,
    category: 'trauma',
    riskFactors: ['trauma', 'osteoporosis', 'elderly'],
    diagnosticCriteria: ['mechanism of injury', 'deformity', 'crepitus', 'X-ray confirmation'],
    medicines: [
      { name: 'Pain relief', dosage: 'IV' },
      { name: 'Antibiotics', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'A fracture is a break in a bone, often caused by trauma or underlying bone disease.',
    complications: ['Infection', 'Malunion'],
  },
  {
    name: 'Concussion',
    symptoms: ['headache', 'confusion', 'dizziness', 'nausea', 'memory problems', 'sensitivity to light'],
    severity: 65,
    category: 'trauma',
    riskFactors: ['head trauma', 'sports injury', 'falls'],
    diagnosticCriteria: ['head trauma + altered consciousness', 'amnesia', 'confusion'],
    medicines: [
      { name: 'Pain relief', dosage: 'IV' },
      { name: 'Antibiotics', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'A concussion is a type of traumatic brain injury that affects the brain function.',
    complications: ['Post-concussion syndrome', 'Chronic traumatic encephalopathy'],
  },
  {
    name: 'Venomous Snake Bite',
    symptoms: ['fang marks', 'severe pain', 'swelling', 'bleeding', 'nausea', 'difficulty breathing', 'ptosis'],
    severity: 95,
    category: 'trauma',
    riskFactors: ['rural area', 'farming', 'walking barefoot'],
    diagnosticCriteria: ['bite marks', 'local swelling', 'systemic symptoms', 'coagulopathy'],
    medicines: [
      { name: 'Antivenom', dosage: 'IV' },
      { name: 'Oxygen', dosage: 'High flow' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'A venomous snake bite can cause severe local and systemic effects, including pain, swelling, and bleeding.',
    complications: ['Coagulopathy', 'Renal failure'],
  },

  // METABOLIC & ENDOCRINE
  {
    name: 'Diabetic Ketoacidosis',
    symptoms: ['extreme thirst', 'frequent urination', 'nausea', 'vomiting', 'abdominal pain', 'fruity breath', 'confusion'],
    severity: 90,
    category: 'metabolic',
    riskFactors: ['type 1 diabetes', 'insulin non-compliance', 'infection'],
    diagnosticCriteria: ['blood glucose > 250 mg/dL', 'ketones in urine', 'metabolic acidosis'],
    medicines: [
      { name: 'Insulin', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
      { name: 'Electrolytes', dosage: 'IV' },
    ],
    description: 'Diabetic ketoacidosis is a complication of diabetes where the body produces excess ketones, leading to acidosis.',
    complications: ['Hypovolemic shock', 'Cerebral edema'],
  },
  {
    name: 'Hypoglycemia',
    symptoms: ['shakiness', 'sweating', 'rapid heartbeat', 'anxiety', 'confusion', 'hunger', 'dizziness'],
    severity: 75,
    category: 'metabolic',
    riskFactors: ['diabetes medication', 'skipped meals', 'excessive exercise'],
    diagnosticCriteria: ['blood glucose < 70 mg/dL', 'symptoms resolve with glucose'],
    medicines: [
      { name: 'Glucose', dosage: 'IV' },
      { name: 'Insulin', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Hypoglycemia is a condition where blood sugar levels are abnormally low, leading to symptoms such as shakiness and confusion.',
    complications: ['Seizures', 'Coma'],
  },
  {
    name: 'Hypertensive Crisis',
    symptoms: ['severe headache', 'chest pain', 'shortness of breath', 'nosebleed', 'anxiety', 'blurred vision'],
    severity: 88,
    category: 'cardiac',
    riskFactors: ['uncontrolled hypertension', 'medication non-compliance'],
    diagnosticCriteria: ['BP > 180/120 mmHg', 'target organ damage'],
    medicines: [
      { name: 'Nitroglycerin', dosage: '0.4mg sublingual' },
      { name: 'Labetalol', dosage: '10mg IV' },
      { name: 'Morphine', dosage: '5mg IV' },
    ],
    description: 'Hypertensive crisis is a severe elevation in blood pressure that can lead to organ damage.',
    complications: ['Stroke', 'Heart attack'],
  },

  // COMMON CONDITIONS
  {
    name: 'Common Cold (Viral URTI)',
    symptoms: ['runny nose', 'sneezing', 'sore throat', 'cough', 'mild fever', 'congestion'],
    severity: 25,
    category: 'respiratory',
    riskFactors: ['close contact', 'cold weather', 'low immunity'],
    diagnosticCriteria: ['gradual onset', 'rhinorrhea', 'self-limiting < 10 days'],
    medicines: [
      { name: 'Paracetamol', dosage: '500-1000mg' },
      { name: 'Decongestants', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'The common cold is a viral infection of the upper respiratory tract, causing symptoms such as runny nose and cough.',
    complications: ['Sinusitis', 'Otitis media'],
  },
  {
    name: 'Influenza',
    symptoms: ['high fever', 'severe body ache', 'headache', 'fatigue', 'dry cough', 'sore throat'],
    severity: 55,
    category: 'infectious',
    riskFactors: ['no vaccination', 'seasonal outbreak', 'crowded places'],
    diagnosticCriteria: ['sudden onset fever > 38°C', 'myalgia', 'respiratory symptoms'],
    medicines: [
      { name: 'Oseltamivir', dosage: '75mg' },
      { name: 'Paracetamol', dosage: '500-1000mg' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Influenza is a viral infection that causes fever, cough, and body aches.',
    complications: ['Pneumonia', 'Myocarditis'],
  },
  {
    name: 'Urinary Tract Infection',
    symptoms: ['burning urination', 'frequent urination', 'cloudy urine', 'lower abdominal pain', 'fever'],
    severity: 52,
    category: 'infectious',
    riskFactors: ['female', 'sexual activity', 'diabetes', 'catheter use'],
    diagnosticCriteria: ['dysuria', 'frequency', 'positive urine culture'],
    medicines: [
      { name: 'Nitrofurantoin', dosage: '100mg' },
      { name: 'Fluids', dosage: 'IV' },
      { name: 'Pain relief', dosage: 'IV' },
    ],
    description: 'A urinary tract infection (UTI) is an infection in any part of the urinary system, causing symptoms such as burning urination and pain.',
    complications: ['Pyelonephritis', 'Sepsis'],
  },
  {
    name: 'Tension Headache',
    symptoms: ['band-like headache', 'bilateral pain', 'neck stiffness', 'scalp tenderness'],
    severity: 30,
    category: 'neurological',
    riskFactors: ['stress', 'poor posture', 'lack of sleep', 'eye strain'],
    diagnosticCriteria: ['bilateral pressing/tightening pain', '30 min - 7 days duration', 'no nausea/vomiting'],
    medicines: [
      { name: 'Paracetamol', dosage: '500-1000mg' },
      { name: 'Ibuprofen', dosage: '200-400mg' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'A tension headache is a common type of headache that causes a dull, aching pain on both sides of the head.',
    complications: ['Chronic tension headaches'],
  },
  {
    name: 'Allergic Rhinitis',
    symptoms: ['sneezing', 'runny nose', 'itchy eyes', 'nasal congestion', 'postnasal drip'],
    severity: 28,
    category: 'other',
    riskFactors: ['allergen exposure', 'family history', 'asthma'],
    diagnosticCriteria: ['symptoms after allergen exposure', 'clear nasal discharge', 'itching'],
    medicines: [
      { name: 'Cetirizine', dosage: '10mg' },
      { name: 'Fluticasone', dosage: '50mcg' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Allergic rhinitis, also known as hay fever, is an allergic reaction to airborne allergens, causing symptoms such as sneezing and runny nose.',
    complications: ['Sinusitis', 'Asthma'],
  },
  {
    name: 'Contact Dermatitis',
    symptoms: ['red rash', 'itching', 'blisters', 'dry skin', 'swelling'],
    severity: 25,
    category: 'other',
    riskFactors: ['allergen contact', 'sensitive skin', 'occupational exposure'],
    diagnosticCriteria: ['rash at contact site', 'pruritus', 'vesicles/scaling'],
    medicines: [
      { name: 'Corticosteroids', dosage: 'IV' },
      { name: 'Antihistamines', dosage: 'IV' },
      { name: 'Fluids', dosage: 'IV' },
    ],
    description: 'Contact dermatitis is a skin reaction that occurs when the skin comes into contact with an irritant or allergen.',
    complications: ['Secondary infections', 'Scarring'],
  },
];

// Medicine Database with detailed information
export const MEDICINE_DATABASE: Record<string, MedicineRecommendation> = {
  'Paracetamol': {
    name: 'Paracetamol (Acetaminophen)',
    dosage: '500-1000mg',
    frequency: 'Every 6-8 hours',
    duration: 'As needed, max 3 days without doctor',
    contraindications: ['Severe liver disease', 'Chronic alcoholism', 'Allergy to paracetamol'],
    sideEffects: ['Rare: Rash', 'Liver damage (overdose)'],
    instructions: 'Take with water. Can take with or without food. Max 4000mg/day.',
  },
  'Ibuprofen': {
    name: 'Ibuprofen',
    dosage: '200-400mg',
    frequency: 'Every 6-8 hours',
    duration: 'Max 10 days',
    contraindications: ['Stomach ulcer', 'Kidney disease', 'Heart disease', 'Pregnancy (3rd trimester)', 'Aspirin allergy'],
    sideEffects: ['Stomach upset', 'Heartburn', 'Dizziness', 'Kidney problems (long-term)'],
    instructions: 'ALWAYS take with food or milk. Avoid if dengue suspected.',
  },
  'Aspirin': {
    name: 'Aspirin (Acetylsalicylic Acid)',
    dosage: '75-325mg',
    frequency: 'Once daily (low dose) or as directed',
    duration: 'As prescribed by doctor',
    contraindications: ['Children < 12 years', 'Bleeding disorders', 'Stomach ulcer', 'Dengue fever', 'Severe liver disease'],
    sideEffects: ['Stomach bleeding', 'Easy bruising', 'Ringing in ears'],
    instructions: 'For heart attack: CHEW 300mg immediately. Never give to children with fever.',
  },
  'Cetirizine': {
    name: 'Cetirizine',
    dosage: '10mg',
    frequency: 'Once daily at bedtime',
    duration: 'As needed',
    contraindications: ['Severe kidney disease', 'Known allergy'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Fatigue'],
    instructions: 'May cause drowsiness - avoid driving. Non-drowsy during day: use loratadine.',
  },
  'Omeprazole': {
    name: 'Omeprazole',
    dosage: '20-40mg',
    frequency: 'Once daily before breakfast',
    duration: '7-14 days (max 4 weeks without doctor)',
    contraindications: ['Known allergy', 'Severe liver disease'],
    sideEffects: ['Headache', 'Diarrhea', 'Nausea', 'Vitamin B12 deficiency (long-term)'],
    instructions: 'Take 30 minutes before food. Swallow whole, do not crush.',
  },
  'ORS': {
    name: 'Oral Rehydration Solution (ORS)',
    dosage: '200-400ml after each loose stool',
    frequency: 'Frequent small sips',
    duration: 'Until diarrhea stops',
    contraindications: ['Intestinal obstruction', 'Severe vomiting'],
    sideEffects: ['None significant'],
    instructions: 'Mix 1 sachet in 1 liter clean water. Prepare fresh every 24 hours.',
  },
  'Salbutamol': {
    name: 'Salbutamol (Albuterol) Inhaler',
    dosage: '2-4 puffs',
    frequency: 'Every 4-6 hours as needed',
    duration: 'As needed for symptoms',
    contraindications: ['Known allergy', 'Severe heart disease'],
    sideEffects: ['Tremor', 'Rapid heartbeat', 'Nervousness'],
    instructions: 'Shake well. Breathe out fully, inhale slowly while pressing. Hold breath 10 seconds.',
  },
  'Azithromycin': {
    name: 'Azithromycin',
    dosage: '500mg',
    frequency: 'Once daily',
    duration: '3-5 days',
    contraindications: ['Severe liver disease', 'Allergy to macrolides'],
    sideEffects: ['Diarrhea', 'Nausea', 'Abdominal pain'],
    instructions: 'Complete full course. Take 1 hour before or 2 hours after food.',
  },
  'Amoxicillin': {
    name: 'Amoxicillin',
    dosage: '500mg',
    frequency: '3 times daily',
    duration: '5-7 days',
    contraindications: ['Penicillin allergy', 'Glandular fever'],
    sideEffects: ['Diarrhea', 'Rash', 'Nausea'],
    instructions: 'Complete full course even if feeling better. Take with food.',
  },
  'Metformin': {
    name: 'Metformin',
    dosage: '500-850mg',
    frequency: 'With meals, 1-2 times daily',
    duration: 'Long-term as prescribed',
    contraindications: ['Severe kidney disease', 'Liver disease', 'Heart failure', 'Alcohol abuse'],
    sideEffects: ['Diarrhea', 'Nausea', 'Metallic taste', 'Lactic acidosis (rare)'],
    instructions: 'Take with meals. Monitor blood sugar. Increase dose gradually.',
  },
  'Amlodipine': {
    name: 'Amlodipine',
    dosage: '5-10mg',
    frequency: 'Once daily',
    duration: 'Long-term as prescribed',
    contraindications: ['Severe low blood pressure', 'Severe aortic stenosis'],
    sideEffects: ['Ankle swelling', 'Flushing', 'Headache', 'Dizziness'],
    instructions: 'Take at same time daily. Don\'t stop suddenly. Monitor blood pressure.',
  },
};